pipeline {

  environment {
    baseImage= "naresh3451213/laravel-hello-1"
    dockerimagename = "${baseImage}:${BUILD_NUMBER}"
    dockerImage = ""
  }

  agent any

  stages {

    stage('Checkout Latest Source') {
      steps {
        git branch: 'main', url: 'https://github.com/beadeveloper9789/devops-task-laravel-cicd-nginx-kubernetes.git'
      }
    }

    stage('Build image') {
      steps{
        dir('app1'){
          script {
            sh 'docker rmi -f ${baseImage}'
            dockerImage = docker.build dockerimagename
          }
        }
      }
    }

    stage('Pushing Image') {
      environment {
               registryCredential = 'dockerhublogin'
           }
      steps{
        script {
          docker.withRegistry('https://registry.hub.docker.com', registryCredential) {
              dockerImage.push("${BUILD_NUMBER}")
              sh 'docker rmi -f ${dockerimagename}'
          }
        }
      }
    }

    

  }

}
